### PR TITLE
Fix prioritization of `given`s over `implicit`s

### LINKED ISSUE #21212: Difference in handling of context bounds and anonymous using arguments
During the minimization of the crash found in OpenCB for https://github.com/takapi327/ldbc I've observed that context bounds and anonymous using arguments are treated differently by the compiler in cases where they're mixed with named using arguments. 
When using context bounds we now get an ambiguous implicit resolution, but it's not the case in when the anonymous using arguments. This behaviour seems strange since both ways of declaring implicit ends up as being synthetic implicit parameters introduced by the compiler. 

## Compiler version
3.6.0-RC1-bin-20240716-bbb45ca-NIGHTLY 

## Minimized code

```Scala
trait Functor[F[_]]:
  def map[A, B](fa: F[A])(f: A => B): F[B] = ???
trait Monad[F[_]] extends Functor[F]
trait MonadError[F[_], E] extends Monad[F]:
  def raiseError[A](e: E): F[A]
trait Temporal[F[_]] extends MonadError[F, Throwable]

trait FunctorOps[F[_], A]:
  def map[B](f: A => B): F[B] = ???
implicit def toFunctorOps[F[_], A](target: F[A])(implicit tc: Functor[F]): FunctorOps[F, A] = ???

class ContextBounds[F[_]: Temporal](using err: MonadError[F, Throwable]):
  def useCase = err.raiseError(new RuntimeException())
  val bool: F[Boolean] = ???
  def fails = toFunctorOps(bool).map(_ => ())  // warns under -source:3.5, // error under -source:3.6

class UsingArguments[F[_]](using Temporal[F])(using err: MonadError[F, Throwable]):
  def useCase = err.raiseError(new RuntimeException())
  val bool: F[Boolean] = ???
  def works = toFunctorOps(bool).map(_ => ()) // warns under -source:3.5

```

### -source:3.5

```scala
[warn] ./src/main/scala/test.scala:15:33
[warn] Given search preference for Functor[F] between alternatives (ContextBounds.this.evidence$1 : Temporal[F]) and (ContextBounds.this.err : MonadError[F, Throwable]) will change
[warn] Current choice           : the first alternative
[warn] New choice from Scala 3.6: none - it's ambiguous
[warn]   def fails = toFunctorOps(bool).map(_ => ())  // warns under -source:3.5, // error under -source:3.6
[warn]                                 ^
[warn] ./src/main/scala/test.scala:20:33
[warn] Given search preference for Functor[F] between alternatives (UsingArguments.this.x$1 : Temporal[F]) and (UsingArguments.this.err : MonadError[F, Throwable]) will change
[warn] Current choice           : the first alternative
[warn] New choice from Scala 3.6: the second alternative
[warn]   def works = toFunctorOps(bool).map(_ => ()) // warns under -source:3.5
[warn]                                 ^
```

### -source:3.6 

```scala
[error] ./src/main/scala/test.scala:15:33
[error] Ambiguous given instances: both value evidence$1 in class ContextBounds and given instance err in class ContextBounds match type Functor[F] of parameter tc of method toFunctorOps
[error]   def fails = toFunctorOps(bool).map(_ => ())  // warns under -source:3.5, // error under -source:3.6
[error]                
```

## Expectation
There might be a hole in implicit resolution logic that should be fixed.

### PR DESCRIPTION
**Pull request by EugeneFlesselle**
- Fix a typo in `Applications#compare#isAsGood#isGiven` which always used `alt1`, to determine if the altneratives passed to `isAsGoodValueType` were givens.

- Update `isAsGoodValueType` to not prefer givens over extensions, by negating the `isGiven` parameter, letting extensions and givens now have the same priority level as far as that rule is concerned.

- Modify `given`/`implicit` definitions from the `Namer` and the [`PPrint`](https://github.com/dotty-staging/PPrint) community-project to resolve ambiguity errors introduced by the changes. 
See the commit message [there]( https://github.com/dotty-staging/PPrint/compare/2203dc6081f5e8fa89f552b155724b0a8fdcec03...34a777f687bc851953e682f99edcae9d2875babc#diff-d18970f29be02f5755463f09892b48c21b29ad72cc2d4af5db059602d0ecfd39) for details on changes to the community-build.

Fixes #21212

### CODE REVIEW

**Review by odersky — COMMENTED** [review]
I am not sure how the code changes relate to the description in the PR. AFAIK, the only changes apply to extension methods, which are now treated as equivalent to givens, where before they were equivalent to extension methods.

Is there another change that I have overlooked?

**Comment by EugeneFlesselle** [comment]
> Is there another change that I have overlooked?

The changes in the first commit https://github.com/scala/scala3/pull/21226/commits/9ec671bde4db299bf0f2a7e8d4ea023343aaf4a3 are only fixing what I assumed was a typo in `isGiven` which was using the captured `alt1` instead of the parameter `alt`:
https://github.com/scala/scala3/blob/d48ba033d8128e04727dbee88a5a8eb3fa98d26d/compiler/src/dotty/tools/dotc/typer/Applications.scala#L1824-L1825

That change fixes the issue in #21212 by now applying the logic prioritizing givens over implicit as intended in #19300.
Unfortunately that change seems to also cause errors with bootstrapping

**Comment by EugeneFlesselle** [comment]
The second commit addresses another error which was encountered following the first commit, namely that when `isAsGoodValueType` is called with an extension and a given conversion, it will prefer the conversion over the extension because only the former `isGiven`. 
Which contradicted the logic from `searchImplicit` which preferred extension over conversions for member selection.

**Comment by odersky** [comment]
Ah, since the whole definition of `isGiven` was dropped I overlooked that change!

**Comment by EugeneFlesselle** [comment]
> Ah, since the whole definition of `isGiven` was dropped I overlooked that change!

No worries, I've updated the commit messages so the changes will hopefully be clearer for the commit history

**Review by odersky — APPROVED** [review]

**Comment by WojciechMazur** [comment]
@EugeneFlesselle this now causes  a warning under -source:3.5 (so also in 3.5.x backports) in https://github.com/scala/scala3/blob/a64c2956f83f8dc53c0bfd7707df4a6e27cd0796/tests/pos/not-looping-implicit.scala
I wonder if this change might be more invasive than expected

```scala
-- Warning: /Users/wmazur/projects/sandbox/src/main/scala/test.scala:49:59 -----
49 |  implicit lazy val inputValueSchema: Schema[InputValue] = Schema.gen
   |                                                           ^^^^^^^^^^
   |Given search preference for Schema[List[InputValue]] between alternatives (Schema.gen : [A]: Schema[A]) and (Schema.listSchema : [A](implicit ev: Schema[A]): Schema[List[A]]) will change
   |Current choice           : the second alternative
   |New choice from Scala 3.6: the first alternative
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:23
23 |        val builder     = summonInline[Schema[t]].asInstanceOf[Schema[Any]]
   |                                       ^^^^^^^^^
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:23
34 |        lazy val fields           = recurse[m.MirroredElemLabels, m.MirroredElemTypes]()
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:23
38 |  inline given gen[A]: Schema[A] = derived[A]
   |                                   ^^^^^^^^^^
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:23
23 |        val builder     = summonInline[Schema[t]].asInstanceOf[Schema[Any]]
   |                                       ^
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:23
31 |        lazy val members     = recurse[m.MirroredElemLabels, m.MirroredElemTypes]()
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:23
38 |  inline given gen[A]: Schema[A] = derived[A]
   |                                   ^^^^^^^^^^
    ----------------------------------------------------------------------------
``` 

I'll start the OpenCB to check it on the bigger number of codebases

**Comment by odersky** [comment]
This should not warn. The logic is wrong here. We should _always_ prefer givens over implicits. The current logic makes implicits more general than givens, which means they will be chosen because we now prefer more general. It should probably be the reverse; we should make implicits more _specific_ than givens.

**Comment by EugeneFlesselle** [comment]
Minimization:
```scala
@main def Test =
  implicit def list[A](using A): List[A] = ???
  inline given gen[A]: A = ???

  given Int = ???
  summon[List[Int]]
  // Resolves to `list[Int](using given_Int)` in 3.5
  // Resolves to `gen[Nothing]`               in 3.6
  // And both versions warn about the changes correctly
```

> We should always prefer givens over implicits. The current logic makes implicits more general than givens, which means they will be chosen because we now prefer more general.

Agreed! and this is indeed what we get here as far as I can tell. We used to pick `list`, but know pick `gen` since it the only given of two, which we prefer in the new rules. The warning would then correct, unless there is something I missed ?

**Comment by EugeneFlesselle** [comment]
This should **not** be backported for 3.5, the original change this amended #19300 has been delayed to being a warning a 3.6 and change in 3.7.

**Pull request merged**
