### PR TITLE
Update MAINTENANCE.md

### PR DESCRIPTION
**Pull request by bracevac**
Update the topic areas and responsible internal team members

### CODE REVIEW

**Comment by hamzaremmal** [comment]
We don't have the issue supervisor role anymore... (See the begining of the document)

**Review by lrytz — APPROVED** [review]

**Comment by bracevac** [comment]
> We don't have the issue supervisor role anymore... (See the begining of the document)

Do we want to get rid of that @Gedochao ?

**Comment by Gedochao** [comment]
> > We don't have the issue supervisor role anymore... (See the begining of the document)
> 
> Do we want to get rid of that @Gedochao ?

Sure. Either here, or a subsequent PR.
Technically, the issue supervisor's part is still there in a way, as it got merged into the Product Manager role.
As in, I guess we can just mention it's me doing it.

**Comment by hamzaremmal** [comment]
> Technically, the issue supervisor's part is still there in a way, as it got merged into the Product Manager role

But all of this is outdated

https://github.com/scala/scala3/blob/main/MAINTENANCE.md?plain=1#L27-L62

**Pull request merged**
