### PR TITLE
Bound TypeRepr by Matchable in Quotes

### LINKED ISSUE #21282: `-source:future-migration` generating warnings on `TypeRepr` matches
## Compiler version

3.4.2

## Minimized example

```scala
import scala.quoted.*

private def isUnionCanonicalImpl[U: Type](using Quotes): Expr[Unit] =
  import quotes.reflect.*
  val u = TypeRepr.of[U].dealiasKeepOpaques

  def inner[U: Type](s: Set[TypeRepr], tr: TypeRepr): Set[TypeRepr] =
    tr.dealiasKeepOpaques match
      case OrType(a, b) =>
        val ss = inner[U](s, a)
        inner[U](ss, b)
      case x if s.contains(x) =>
        report.errorAndAbort(s"Type ${x.show} multiple times (CHECK ALIASES) in union ${u.show}")
      case x => s + x
  inner(Set.empty, u)
  '{ () }
```

```scala
// build.sbt
scalacOptions ++= Seq(
  "-source:future-migration"
)
```
https://scastie.scala-lang.org/wKXmWPdTT2u4crw5NBy3wQ

## Output Error/Warning message

Couldn't find an easy way to get full text version of scatie warning
image
```
[warn] 59 |      case OrType(a, b) =>
[warn]    |           ^^^^^^^^^^^^
[warn]    |           pattern selector should be an instance of Matchable,,
[warn]    |           but it has unmatchable type x$1.reflect.TypeRepr instead
```
## Expected

no warning?

### PR DESCRIPTION
**Pull request by hamzaremmal**
Closes #21282

### CODE REVIEW

**Comment by sjrd** [comment]
Is that not intended? Can we safely match on `TypeRepr`s?

**Review by jchyb — APPROVED** [review]
LGTM. Thank you!
We might need to go through some other types in Quotes.scala like ImplicitSearchResult, Tree, even some TypeRepr subtypes like AndOrType and also add `Matchable` there. I'll try to prepare an issue for that and fix it later today.

**Comment by hamzaremmal** [comment]
> LGTM. Thank you! We might need to go through some other types in Quotes.scala like ImplicitSearchResult, Tree, even some TypeRepr subtypes like AndOrType and also add `Matchable` there. I'll try to prepare an issue for that and fix it later today.

I agree, I'm sure there are some other types we need to bind but I didn't want to include these changes here as it closes a specific issue. We don't need to do anything more for subtypes of `TypeRepr`, the will all be bound by `Matchable` since now `TypeRepr` is bound by `Matchable`: 
https://github.com/scala/scala3/blob/b64afadb6c4301bfd3328fcac77611156c756b7e/library/src/scala/quoted/Quotes.scala#L2997

For `Tree` and `ImplicitSearchResult`, the type is already bound by `AnyRef` and therefore `Matchable`:

https://github.com/scala/scala3/blob/b64afadb6c4301bfd3328fcac77611156c756b7e/library/src/scala/quoted/Quotes.scala#L283

https://github.com/scala/scala3/blob/b64afadb6c4301bfd3328fcac77611156c756b7e/library/src/scala/quoted/Quotes.scala#L3711

Nevertheless, a check is welcome.

**Comment by jchyb** [comment]
Ah, good point!

**Pull request merged**
