### PR TITLE
In progress: transfer of the repository to scala/scala3

### PR DESCRIPTION
**Pull request by hamzaremmal**
This PR is part of the upcoming transfer of the `lampepfl/dotty` repository to the `scala` organisation (`scala/scala3`).

### CODE REVIEW

**Comment by hamzaremmal** [comment]
<h3 align=center> Protocol for transfering lampepfl/dotty to scala/scala3 </h3>
<h4 align=center> By @hamzaremmal and @sjrd </h4>

---

1. Remove all the runners from `lampepfl/dotty` repository.
We need to make sure that the runners don't execute any job when they are transferred.
To check this: https://github.com/organizations/lampepfl/settings/actions/runners

2. Transfer the repository to the `scala` organization.
The renaming of the repository should be done at that moment, not later.
(We believe that this is important for redirections; dry-run was completed this way).

3. Copy and link all the `GitHub Projects` related to `lampepfl/dotty`. The projects are the following:
- [Scala 3.3 LTS Backporting](https://github.com/orgs/lampepfl/projects/6)
- [Scala 3.Next](https://github.com/orgs/lampepfl/projects/8)
- [Scala 3.x planning](https://github.com/orgs/lampepfl/projects/2)

4. Only allow the `scala/scala3` repository to use the custom runners in the `scala` organization settings.

5. Once we confirm that the runners are up in the `scala` organization (and that GitHub Actions is still enabled),
we merge the following PR (https://github.com/lampepfl/dotty/pull/19839) to switch the
configuration from `lampepfl/dotty` to `scala/scala3`.

6. (Probably Nothing) @Kordyjan: Check if the `backport to LTS project` workflow is still working.
We weren't able to test this during the dry-run. (**Not a blocker**).

7. A few links to remove:
- Remove the link to `lampepfl/dotty` in `.github/profile/`
See PR (https://github.com/scala/.github/pull/2)
- Remove the link to `lampepfl/dotty` in the `scala/scala` repository (About section)

8. Add warning in the `.github-private` of `lampepfl` ([More info](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-member-only-organization-profile-readme)) to never create
a repository with the name `dotty`.
**This is important for the redirections**.

9. Grant the correct access to the repository for:
  - `scala3-commiters`: Should be granted `Write` role
  - `scala3-admins`: Should be granted `Admin` role
  (Same system as for the Scala 2 repository)

10. Delete the `scala3-transfer-test` repository from the `scala` organization.

##### Benchmarking infrastructure:
 @mbovel will do the necessary after the transfer.

**Comment by hamzaremmal** [comment]
Second commit in this PR is not important to have a successful transfer. 
Note to myself: Should I move it to a different PR ?

**Comment by SethTisue** [comment]
This is really minor, but once it's transferred, it should also become of the "pinned" repos at https://github.com/scala . (I just unpinned something else to make room for it.)

**Comment by hamzaremmal** [comment]
> This is really minor, but once it's transferred, it should also become of the "pinned" repos at https://github.com/scala . (I just unpinned something else to make room for it.)

I had it in mind but I forgot to add it in the protocol. Just did.

**Comment by SethTisue** [comment]
s/commiters/committers

**Comment by SethTisue** [comment]
about teams and permissions, if people feel that there should be Scala 3 specific GitHub teams, for permissions purposes, I certainly don't object. but if it's being kept separate out of fear that you'll, like, step on Lightbend's toes, or disruption tradition, or anything like that, you really needn't worry, it's fine

**Comment by sjrd** [comment]
> Second commit in this PR is not important to have a successful transfer. Note to myself: Should I move it to a different PR ?

I suggest we keep it for a separate PR that we'll do once we have confirmed that we have a working CI after the migration. This way, we will actually get a proper CI run of these additional changes.

**Comment by hamzaremmal** [comment]
> > Second commit in this PR is not important to have a successful transfer. Note to myself: Should I move it to a different PR ?
> 
> 
> 
> I suggest we keep it for a separate PR that we'll do once we have confirmed that we have a working CI after the migration. This way, we will actually get a proper CI run of these additional changes.

Agreed 👍

**Comment by sjrd** [comment]
> about teams and permissions, if people feel that the right thing is to have Scala 3 specific GitHub teams, for permissions purposes, then great, I certainly don't object. but if it's being kept separate out of fear that you'll, like, step on Lightbend's toes, or disrupt tradition, or anything like that, you really needn't worry, it's fine, let's do whatever makes sense and isn't overly elaborate. cc @lrytz

IMO we could do that in a second phase. I'd like to minimize the amount of changes that we have to do at the time of the migration itself.

**Comment by hamzaremmal** [comment]
Second commit was moved to the following PR:
- https://github.com/lampepfl/dotty/pull/19864

**Review by sjrd — APPROVED** [review]

**Comment by hamzaremmal** [comment]
@Kordyjan This PR needs to be backported ASAP to the LTS branch (to have the new configuration setup).

It should also be backported to any active release branch too (mainly `release-3.4.1`)

**Comment by Kordyjan** [comment]
> @Kordyjan This PR needs to be backported ASAP to the LTS branch (to have the new configuration setup).

Backported to all relevant branches.

**Comment by Kordyjan** [comment]
> Check if the backport to LTS project workflow is still working.

Looks like it follows the redirects correctly, so nothing urgent to do here.

**Comment by hamzaremmal** [comment]
> > Check if the backport to LTS project workflow is still working.
> 
> Looks like it follows the redirects correctly, so nothing urgent to do here.

@Kordyjan There is a new project in the scala organization (https://github.com/orgs/scala/projects/2). The other one still has all the old PRs and we will be retiring it slowly. New PRs should go to this new project.

**Pull request merged**
