### PR TITLE
fix: Check if a PolyFunction TypeTree has no ByName parameters

### LINKED ISSUE #21652: Crashes when defining a polymorphic function with by name parameters: `assertion failed: Not a valid PolyFunction refinement`
## Compiler version

3.5.1

## Minimized code

```Scala
def k: [A] => (=> A) => [B] => (=> B) => A = { [A] => a => [B] => b =>
  lazy val lazyA = a
  lazyA
}
```

## Output (click arrow to expand)

<details>

```
[info] compiling 1 Scala source to /home/nixos/m-combinator.scala/target/scala-3.5.1/classes ...
[info] 
[info]   exception occurred while typechecking /home/nixos/m-combinator.scala/M.scala
[info] 
[info]   An unhandled exception was thrown in the compiler.
[info]   Please file a crash report here:
[info]   https://github.com/scala/scala3/issues/new/choose
[info]   For non-enriched exceptions, compile with -Xno-enrich-error-messages.
[info] 
[info]      while compiling: /home/nixos/m-combinator.scala/M.scala
[info]         during phase: typer
[info]                 mode: Mode(ImplicitsEnabled)
[info]      library version: version 2.13.14
[info]     compiler version: version 3.5.1
[info]             settings: -classpath /home/nixos/m-combinator.scala/target/scala-3.5.1/classes:/home/nixos/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.5.1/scala3-library_3-3.5.1.jar:/home/nixos/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.14/scala-library-2.13.14.jar -d /home/nixos/m-combinator.scala/target/scala-3.5.1/classes
[error] ## Exception when compiling 1 sources to /home/nixos/m-combinator.scala/target/scala-3.5.1/classes
[error] java.lang.AssertionError: assertion failed: Not a valid PolyFunction refinement: PolyType(List(B), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), MethodType(List(b), List(ExprType(TypeParamRef(B))), TypeRef(NoPrefix,type A)))
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.Definitions$PolyFunctionOf$.apply(Definitions.scala:1205)
[error] dotty.tools.dotc.core.Types$Type.toFunctionType(Types.scala:1978)
[error] dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:425)
[error] dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:16)
[error] dotty.tools.dotc.typer.Typer.assignType(Typer.scala:145)
[error] dotty.tools.dotc.typer.Typer.typedClosure(Typer.scala:1973)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3426)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3691)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1406)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3422)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedPolyFunctionValue(Typer.scala:1923)
[error] dotty.tools.dotc.typer.Typer.typedPolyFunction(Typer.scala:1891)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3425)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3691)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1406)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3422)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3691)
[error] dotty.tools.dotc.typer.Typer.$anonfun$64(Typer.scala:2838)
[error] dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:256)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2838)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3396)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3498)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3602)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3648)
[error] dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1399)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1403)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3422)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedPolyFunctionValue(Typer.scala:1923)
[error] dotty.tools.dotc.typer.Typer.typedPolyFunction(Typer.scala:1891)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3425)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3691)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1406)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3422)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3691)
[error] dotty.tools.dotc.typer.Typer.$anonfun$64(Typer.scala:2838)
[error] dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:256)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2838)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3396)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3498)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3602)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3648)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:3096)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3402)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3406)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3498)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3602)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3648)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:3229)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3448)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3499)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3576)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3580)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3691)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:47)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:503)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:53)
[error] dotty.tools.dotc.typer.TyperPhase.$anonfun$4(TyperPhase.scala:99)
[error] scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:479)
[error] scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
[error] scala.collection.immutable.List.prependedAll(List.scala:152)
[error] scala.collection.immutable.List$.from(List.scala:685)
[error] scala.collection.immutable.List$.from(List.scala:682)
[error] scala.collection.IterableOps$WithFilter.map(Iterable.scala:900)
[error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:98)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:343)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:336)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:384)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:396)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:396)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:282)
[error] dotty.tools.dotc.Run.compile(Run.scala:267)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:194)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:249)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:184)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:164)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:164)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:212)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3(Incremental.scala:178)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3$adapted(Incremental.scala:176)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:454)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:117)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:265)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:409)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:496)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:396)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:170)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2427)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2377)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:41)
[error] sbt.internal.io.Retry$.apply(Retry.scala:47)
[error] sbt.internal.io.Retry$.apply(Retry.scala:29)
[error] sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:41)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2375)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] java.base/java.lang.Thread.run(Thread.java:1583)
[error]            
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed: Not a valid PolyFunction refinement: PolyType(List(B), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), MethodType(List(b), List(ExprType(TypeParamRef(B))), TypeRef(NoPrefix,type A)))
[error] Total time: 0 s, completed Sep 26, 2024, 5:27:02 PM
```
</details>

### PR DESCRIPTION
**Pull request by KacperFKorban**
closes #21652

### CODE REVIEW

**Comment by mbovel** [comment]
I see that there is already `Checking.checkPolyFunctionType` that is supported to check that. So I'm wondering: couldn't we just comment the assertion in `PolyFunctionOf.apply`, and let `PostTyper` check that? I tried and it seems to work for this specific example:

```scala
-- Error: test.scala:1:8 -------------------------------------------------------
1 |def k: [A] => (=> A) => A = // error
  |        ^^^^^^^^^^^^^^^^^
  |Implementation restriction: PolyFunction apply must have exactly one parameter list and optionally type arguments. No by-name nor varags are allowed.
1 error found
```

**Comment by KacperFKorban** [comment]
Good idea, less code is always better. I'm not sure about removing the assertion entirely. These types of assertions are pretty useful so that when something crashes, the error is thrown pretty early and not in an unrelated phase. Maybe just the byname and varargs part?

**Comment by KacperFKorban** [comment]
Hmmm, actually it doesn't work for me. It compiles without any errors by default and crashed after some later phase with `-Ycheck:all`

**Comment by mbovel** [comment]
Strange, have we tried the same change?

```
➜  ~/dotty git:(main) ✗ cat 21671.scala    
def k: [A] => (=> A) => A = // error
   [A] => a => a
➜  ~/dotty git:(main) ✗ git rev-parse HEAD    
c33276637e39e71c13e049d907b239d03a98ad5d
➜  ~/dotty git:(main) ✗ git --no-pager diff           
diff --git a/compiler/src/dotty/tools/dotc/core/Definitions.scala b/compiler/src/dotty/tools/dotc/core/Definitions.scala
index f95bb3cea3..c5b7aa5897 100644
--- a/compiler/src/dotty/tools/dotc/core/Definitions.scala
+++ b/compiler/src/dotty/tools/dotc/core/Definitions.scala
@@ -1221,7 +1221,7 @@ class Definitions {
 
     /** Creates a refined `PolyFunction` with an `apply` method with the given info. */
     def apply(mt: MethodOrPoly)(using Context): Type =
-      assert(isValidPolyFunctionInfo(mt), s"Not a valid PolyFunction refinement: $mt")
+      //assert(isValidPolyFunctionInfo(mt), s"Not a valid PolyFunction refinement: $mt")
       RefinedType(PolyFunctionClass.typeRef, nme.apply, mt)
 
     /** Matches a refined `PolyFunction` type and extracts the apply info.
➜  ~/dotty git:(main) ✗ sbt "scalac 21671.scala"
...
-- Error: 21671.scala:1:8 ------------------------------------------------------
1 |def k: [A] => (=> A) => A = // error
  |        ^^^^^^^^^^^^^^^^^
  |Implementation restriction: PolyFunction apply must have exactly one parameter list and optionally type arguments. No by-name nor varags are allowed.
...
```

**Comment by KacperFKorban** [comment]
Oooh, actually nevermind. It works, but the `isValidPolyFunctionInfo` is reused in `Checking`, so just removing the by-name and vararg checks doesn't work.

**Review by mbovel — APPROVED** [review]

**Pull request merged**
