### PR TITLE
Fix failing `CompletionScalaCliSuite` tests due to circe releasing Scala Native 0.5 artifacts

### PR DESCRIPTION
**Pull request by WojciechMazur**
The recent release of circe for SN 0.5 changed the outputs of CompletionScalaCli suite. The PR fixes failing tests

### CODE REVIEW

**Review by rochala — APPROVED** [review]
We should find a better way to handle this kind of completions.

@tgodzik Coursier is quite big dependency and we only use it for this purpose. Maybe we could change the interface in a way that allows us to provide a handler for this kind of completions, and move away logic form the presentation compiler ?

**Comment by WojciechMazur** [comment]
> We should find a better way to handle this kind of completions.

Agree. It's just a fast fix although it seems that presentation compiler is not tested in the CI (I think so), but it started to fail locally.  In such case if it's not blocking CI we can take time to make a better solution

**Comment by WojciechMazur** [comment]
Surprisingly the CI failed in all of the modified tests. We would need to check why it behaves differently locally and in the CI

**Comment by tgodzik** [comment]
> Surprisingly the CI failed in all of the modified tests. We would need to check why it behaves differently locally and in the CI

That is highly surprising, this is basically cs complete-dep and its' output seems to work

> We should find a better way to handle this kind of completions.
> 
> @tgodzik Coursier is quite big dependency and we only use it for this purpose. Maybe we could change the interface in a way that allows us to provide a handler for this kind of completions, and move away logic form the presentation compiler ?

We could add that to SymbolSearch interface, it would probably make sense and just mock it, test it inside metals

**Comment by tgodzik** [comment]
If needed you can ignore the tests for now.

**Comment by hamzaremmal** [comment]
Blocking #20837

**Pull request merged**
