### PR TITLE
Set default source version to 3.5

### LINKED ISSUE #20415: New implicit resolution warning mentions "This will be an error in Scala 3.5 and later." but is not an error in 3.5.0-RC1
## Compiler version

3.5.0-RC1

## Minimized code

```Scala
class Foo:
  given ord: Ordering[Int] = summon[Ordering[Int]]
```

## Output

```scala
  |                                                            ^
  |Result of implicit search for Ordering[Int] will change.
  |Current result Foo.this.ord will be no longer eligible
  |  because it is not defined before the search position.
  |Result with new rules: scala.math.Ordering.Int.
  |To opt into the new rules, compile with `-source future` or use
  |the `scala.language.future` language import.
  |
  |To fix the problem without the language import, you could try one of the following:
  |  - use a `given ... with` clause as the enclosing given,
  |  - rearrange definitions so that Foo.this.ord comes earlier,
  |  - use an explicit argument.
  |This will be an error in Scala 3.5 and later.
```

## Expectation

This should actually be an error. Also, ideally I'd really like to enable the new behavior in my codebase, but `-source future` breaks too many things, can we add it to `-source 3.6` instead?

### PR DESCRIPTION
**Pull request by hamzaremmal**
Superseeds #20435 
Closes #20415 

[test_scala2_library_tasty]
[test_windows_full]
[test_java8]

### CODE REVIEW

**Comment by hamzaremmal** [comment]
**How I fixed it**

First, I've changed the default source version from `3.4` to `3.5`. This change will trigger a number of uses in `scala2-library-bootsrapped` and `scala2-library-cc`. I've then cloned the source code of the scala2 library using the following commands in sbt: `scala2-library-cc/run overwrite <path>` and `scala2-library-bootstrapped/run overwrite <path>` (eg: `scala2-library-cc/run overwrite scala/Array.scala`). After cloning the missing files, I've proceeded with the changes to adapt the library to Scala 3.5

**Comment by hamzaremmal** [comment]
@Kordyjan This PR will need to be backported to the `3.5` release branch and be included in `3.5.0-RC2`

**Comment by odersky** [comment]
@hamzaremmal I added you to dotty-staging/dotty. So in the future you can push your PRs there or add commits to existing PRs.

**Comment by hamzaremmal** [comment]
@odersky Should be good for review now. @natsukagami can you take a look at why semanticdb somtimes incule the diagnostics and sometimes it doesn't (should not block this PR since I commented it for now)

**Comment by odersky** [comment]
@natsukagami That's a great analysis. Let me see if we can somehow delay the warning to the point where we choose one of the implicits that are mentioned in it.

**Comment by odersky** [comment]
See #20480 for a fix that should suppress the spurious warnings.

**Review by odersky — APPROVED** [review]

**Comment by odersky** [comment]
We should remember to re-enable the semanticdb diagnostics when #20480 is merged.

**Comment by hamzaremmal** [comment]
> We should remember to re-enable the semanticdb diagnostics when #20480 is merged.

Indeed, I suggested to do it in the same PR since it was the trigger for this change

**Pull request merged**
