### PR TITLE
Improve documentation of implicit conversions

### PR DESCRIPTION
**Pull request by rjolly**

### CODE REVIEW

**Comment by som-snytt** [comment]
This is from the same discussion. https://github.com/scala/scala3/pull/20091

**Comment by rjolly** [comment]
oh sorry, you were faster than me.

**Comment by rjolly** [comment]
@som-snytt notice my change to the implicit scope specification as well, if you feel it is relevant maybe you could take it in your PR and I will close this one, please tell me.

**Comment by som-snytt** [comment]
I will wait upon @sjrd feedback.

**Review by sjrd — APPROVED** [review]

**Comment by rjolly** [comment]
@sjrd I think this needs to be merged in language-reference-stable to be visible on the website.

**Pull request merged**
