### PR TITLE
Revert "Approximate MatchTypes with lub of case bodies, if non-recursive" in 3.5.0

### PR DESCRIPTION
**Pull request by WojciechMazur**
Reverts #19761 in 3.5.0-RC6 as discussed in #21258 and accepted by the core compiler team.

### CODE REVIEW

**Comment by dwijnand** [comment]
Why is this reverted in 3.5.0?

**Review by dwijnand — CHANGES_REQUESTED** [review]
Why is this reverted in 3.5.0?

**Comment by WojciechMazur** [comment]
Conclusion from last core meeting:
> #19761 will be reverted on every release branch and on the main. Then, we will release a hotfix for the 3.4 line. We will decide what to do with that change before 3.6. We will set up automatic tests to find similar compatibility problems in the future.

**Comment by sjrd** [comment]
In order to elaborate on the *motivation* for that decision. What came out of discussions is:

* The new state after the change looks better per se. We probably want it.
* We definitely revert it in 3.4.x.
* We don't want to ship it in 3.5.0 "just because it's there already". We want to do so very intentionally.
* We don't really have time to do it properly (intentionally, with good accompanying doc, perhaps with migration flags/warnings, etc.) for 3.5.0.
* Therefore we revert in 3.5.x as well, and take the time to do it properly for 3.6.0.

**Pull request merged**
