### PR TITLE
Revert "Set baseVersion to 3.5.1-RC1"

### LINKED ISSUE #20401: Nightly Dotty workflow of 2024-05-14 failed
See https://github.com/scala/scala3/actions/runs/9073074884

### PR DESCRIPTION
**Pull request by hamzaremmal**
Reverts scala/scala3#20392

Closes #20401

### CODE REVIEW

**Comment by hamzaremmal** [comment]
> I believe Mima filters need to be updated for the new base version.

Yes, but 3.5.0-RC1 is not yet in Maven Central. I've reverted the PR as a hot fix and remerge it with the new base version when 3.5.0-RC1 is in Maven Central

**Comment by Kordyjan** [comment]
This is a matter of MiMa's known bug/weird behavior: It treats `3.4.1 => 3.5.0-RC1` as a minor version bump, but `3.4.1 => 3.5.1-RC1` as a patch version bump and reports errors on forward incompatibilities. What I didn't expect was that it auto-merged my PR even though MiMa checks were failing. I was nearly sure that they were required.

I don't get what it has to do with `3.5.0-RC1` being on Maven Central or not. `3.5.1-RC1` is a version that is in development, so it should be set as a base version.

**Comment by hamzaremmal** [comment]
If 3.5.0-RC1 is available, we can do the following [change](https://github.com/scala/scala3/commit/eaf456114e9f049521d5097af356d182293ebf85) to satisfy MiMA.

**Comment by hamzaremmal** [comment]
> What I didn't expect was that it auto-merged my PR even though MiMa checks were failing. I was nearly sure that they were required.

MiMA checks is not a requirement that we enforce for a PR for now. I've asked @Gedochao to add this to tomorrow's core meeting agenda to have a final decision on adding it as a requirement. https://github.com/scala/scala3/pull/20392 is a good argument to make it a requirement.

**Review by Kordyjan — APPROVED** [review]
I was convicned that it is currently the best solution.

**Comment by hamzaremmal** [comment]
Now that 3.5.0-RC1 is in Maven Central, we can apply the correct fix #20404

**Comment by bishabosha** [comment]
@hamzaremmal now can we unrevert this?

**Comment by hamzaremmal** [comment]
@bishabosha I did in #20404

**Comment by hamzaremmal** [comment]
I thought I did in #20404. I've only a PR for that (#20447)

**Pull request merged**
