### PR TITLE
Reinstantiate restriction to transparent inline methods

### LINKED ISSUE #20297: Regression in `getkyo/kyo` for typer
Based on OpenCB failure in `getkyo/kyo` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/8855242584/job/24321563226)

## Compiler version
Last good release: 3.4.2-RC1-bin-20240311-02c2a6e-NIGHTLY
First bad release: 3.4.2-RC1-bin-20240312-3694d95-NIGHTLY
Exact bisect has failed due to errors when building compiler, could be caused by any of:
b28d4c1cbe0a552091be7c83ea82924db636d7b2 
24215819d4ab1e708936118b56c46bbafaba83be

## Minimized code

```Scala
sealed abstract class Kyo[+T, -S]
opaque type <[+T, -S] >: T = T | Kyo[T, S]

extension [T, S](v: T < S)
  inline def map[U, S2](inline f: T => U < S2): U < (S & S2) = ???

class Streams[V]
object Streams:
  def emitValue[V](v: V): Unit < Streams[V] = ???

opaque type Stream[+T, V, -S] = T < (Streams[V] & S)
object Stream:
  extension [T, V, S](s: Stream[T, V, S])
    def reemit[S2, V2](f: V => Unit < (Streams[V2] & S2)): Stream[T, V2, S & S2] = ???
    def filter[S2](f: V => Boolean < S2): Stream[T, V, S & S2] = reemit { v =>
      f(v).map {
        case false => ()
        case true  => Streams.emitValue(v)
      }
    }
```

## Output

```scala
-- [E007] Type Mismatch Error: /Users/wmazur/projects/dotty/bisect/test.scala:18:39 
18 |        case true  => Streams.emitValue(v)
   |                      ^^^^^^^^^^^^^^^^^^^^
   |                      Found:    Unit < Streams[V]
   |                      Required: Unit < (S & S2)
   |
```

## Expectation
Should compile

### LINKED ISSUE #20342: Regression in `augustnagro/magnum` for implicit search
Based on OpenCB failure found in `augustnagro/magnum` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/8945914916/job/24576335892)

## Compiler version
Last good release: 3.4.2-RC1-bin-20240311-02c2a6e-NIGHTLY
First bad release: 3.4.2-RC1-bin-20240312-3694d95-NIGHTLY
Bisect points to b28d4c1cbe0a552091be7c83ea82924db636d7b2

## Minimized code

```Scala
class Repo[EC, E](using defaults: RepoDefaults[EC, E])
trait RepoDefaults[EC, E]
object RepoDefaults:
  inline given genImmutableRepo[E: DbCodec]: RepoDefaults[E, E] = ???
  inline given genRepo[EC: DbCodec, E: DbCodec]: RepoDefaults[EC, E] = ???

trait DbCodec[E]

case class PersonCreator(name: String)
case class Person(id: Long)
given DbCodec[Person] = ???
given DbCodec[PersonCreator] = ???

@main def Test = 
  val personRepo = Repo[PersonCreator, Person]

```

## Output

```scala
[error] ./sandbox.scala:15:47
[error] No best given instance of type RepoDefaults[PersonCreator, Person] was found for parameter defaults of constructor Repo in class Repo.
[error] I found:
[error] 
[error]     RepoDefaults.genImmutableRepo[E](
[error]       /* ambiguous: both given instance given_DbCodec_Person and given instance given_DbCodec_PersonCreator match type DbCodec[E] */
[error]         summon[DbCodec[E]]
[error]     )
[error] 
[error] But both given instance given_DbCodec_Person and given instance given_DbCodec_PersonCreator match type DbCodec[E].
[error]   val personRepo = Repo[PersonCreator, Person]
[error]                                               ^
Error compiling project (Scala 3.5.0-RC1-bin-20240502-05354ba-NIGHTLY, JVM (17))
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by odersky**
Reverts parts of #19922.

Fixes #20342 
Fixes #20297

The logic that we should ignore declared result types of inline methods really only applies to transparent inlines.

### CODE REVIEW

**Comment by odersky** [comment]
It seems this breaks more in the CB. Not sure what to do, I think I'll give this up for now.

**Review by noti0na1 — APPROVED** [review]
I added a test for #20342, and it passes locally as well.
So, LGTM now.

**Comment by odersky** [comment]
@WojciechMazur So, this test fixes two regressions and probably opens two others that were fixed by #19922. Nevertheless, from a point of the program logic this is the right thing to do. Should we merge this (which would revert to the 3.4 and LTS behavior) or test the open CB before that?

**Comment by WojciechMazur** [comment]
I've run the OpenCB, it does in fact reintroduce the 2 regressions mentioned above. Seems to also introduce a new regression in `softwaremill/tapir` (although it released a new version in meantime, so the sources are slightly different)

| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| kalin-rudnicki/harness | 4.1.3 -> 4.2.5 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/9086273868/job/24971983065) | https://github.com/scala/scala3/issues/19415 |
| softwaremill/tapir | 1.10.0 -> 1.10.6 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/9086270259/job/24971929171) | `Cannot find a codec between types: String and T` |
| apache/pekko-connectors | 1.0.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/9086270259/job/24971905700) | https://github.com/scala/scala3/issues/19479 |

**Comment by WojciechMazur** [comment]
Reproduction for `softwaremill/tapir`: 

```scala
final class StrictEqual[V]
final class Less[V]
type LessEqual[V] = Less[V] | StrictEqual[V]

object TapirCodecIron:
  trait ValidatorForPredicate[Value, Predicate]
  trait PrimitiveValidatorForPredicate[Value, Predicate]
      extends ValidatorForPredicate[Value, Predicate]

  given validatorForLessEqual[N: Numeric, NM <: N](using
      ValueOf[NM]
  ): PrimitiveValidatorForPredicate[N, LessEqual[NM]] = ???
  given validatorForDescribedOr[N, P](using
      IsDescription[P]
  ): ValidatorForPredicate[N, P] = ???

  trait IsDescription[A]
  object IsDescription:
    given derived[A]: IsDescription[A] = ???

@main def Test = {
  import TapirCodecIron.{*, given}
  type IntConstraint = LessEqual[3]
  summon[ValidatorForPredicate[Int, IntConstraint]]
}
```

Without `-source` flag it compiles without any warning
Under `-source:3.5` it yields warning: 
```scala
-- Warning: /Users/wmazur/projects/sandbox/tapir.repro.scala:24:51 -------------
24 |  summon[ValidatorForPredicate[Int, IntConstraint]]
   |                                                   ^
   |Given search preference for TapirCodecIron.ValidatorForPredicate[Int, IntConstraint] between alternatives (TapirCodecIron.validatorForDescribedOr :
   |  [N, P]
   |    (using x$1: TapirCodecIron.IsDescription[P]):
   |      TapirCodecIron.ValidatorForPredicate[N, P]
   |) and (TapirCodecIron.validatorForLessEqual :
   |  [N, NM <: N]
   |    (implicit evidence$1: Numeric[N], x$1: ValueOf[NM]):
   |      TapirCodecIron.PrimitiveValidatorForPredicate[N, LessEqual[NM]]
   |) will change
   |Current choice           : the second alternative
   |New choice from Scala 3.6: none - it's ambiguous
1 warning found
```
Under 3.5-migration it fails with compilation errror: 
```scala
-- [E172] Type Error: /Users/wmazur/projects/sandbox/tapir.repro.scala:24:51 ---
24 |  summon[ValidatorForPredicate[Int, IntConstraint]]
   |                                                   ^
   |Ambiguous given instances: both given instance validatorForDescribedOr in object TapirCodecIron and given instance validatorForLessEqual in object TapirCodecIron match type TapirCodecIron.ValidatorForPredicate[Int, IntConstraint] of parameter x of method summon in object Predef
```

Seems like the 3.5-migration flag is treated as the 3.6

**Comment by SethTisue** [comment]
If the broken projects need only add a `transparent` here and there, that’s plausibly a reasonable thing to ask, but I think we'd need the project maintainers to confirm that it's an acceptable change, without unwanted other effects, in the context of their codebases.

**Comment by odersky** [comment]
@SethTisue One of the failing tests (#19415) could be fixed in its minimization by refining the inference scheme. The other is new code  (#19479), using inline givens and could trivially be changed by adding a `transparent`. So I think we are good to merge.

**Pull request merged**
