### PR TITLE
Assert that memberType selects an existing memberType

### LINKED ISSUE #15159: quotes.reflect.memberType can return ClassInfo
### Discussed in https://github.com/lampepfl/dotty/discussions/15157

in the example below, `memberType` returns a `ClassInfo`, which is not exposed in the quotes api, and seems unexpected when pattern matching on a type. It seems that `memberType` should escape this?

<div type='discussions-op-text'>

<sup>Originally posted by **adamw** May 10, 2022</sup>
I'm trying to summon a typeclass instance for each child class of a sealed trait. So far I've got the following code (here simplified):

```scala
import scala.quoted.*
object TestMacro:
  inline def test[T]: Unit = ${ testImpl[T] }
  def testImpl[T: Type](using Quotes): Expr[Unit] =
    import quotes.reflect.*
    val tpe = TypeRepr.of[T]
    tpe.typeSymbol.children.map { childSymbol =>
      val childTpe = tpe.memberType(childSymbol)
      println("Child TypeRepr: " + childTpe)
      childTpe.asType match
        case '[c] =>
          println("Got Type!")
    }
    '{ () }
```

The `childTpe: TypeRepr` is correct, however I get an exception when converting it to a `Type` and trying to get a handle to the type parameter `c` (so that later I can do `Expr.summon[MyTypeClass[c]]`). Using the following invocation:

```scala
sealed trait A
case class X(i: Int) extends A

object Test extends App {
  TestMacro.test[A]
}
```

The output is:

```
Child type: ClassInfo(ThisType(TypeRef(NoPrefix,module class newschema)), class X, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object), TypeRef(ThisType(TypeRef(NoPrefix,module class newschema)),trait A), TypeRef(TermRef(TermRef(NoPrefix,object _root_),object scala),trait Product), TypeRef(ThisType(TypeRef(NoPrefix,module class io)),trait Serializable)))
[info] assertion failure for class X in package sttp.tapir.newschema <:< c, frozen = false
[error] -- Error: Test.scala:33:16
[error] 33 |  TestMacro.test[A]
[error]    |  ^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: ClassInfo(ThisType(TypeRef(NoPrefix,module class newschema)), class X, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object), TypeRef(ThisType(TypeRef(NoPrefix,module class newschema)),trait A), TypeRef(TermRef(TermRef(NoPrefix,object _root_),object scala),trait Product), TypeRef(ThisType(TypeRef(NoPrefix,module class io)),trait Serializable)))
[error]    |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]    |	at dotty.tools.dotc.core.Types$TypeBounds.<init>(Types.scala:5038)
[error]    |	at dotty.tools.dotc.core.Types$RealTypeBounds.<init>(Types.scala:5114)
[error]    |	at dotty.tools.dotc.core.Types$TypeBounds$.apply(Types.scala:5158)
[error]    |	at dotty.tools.dotc.core.Types$TypeBounds.derivedTypeBounds(Types.scala:5046)
[error]    |	at dotty.tools.dotc.core.ConstraintHandling.addOneBound(ConstraintHandling.scala:262)
[error]    |	at dotty.tools.dotc.core.ConstraintHandling.addOneBound$(ConstraintHandling.scala:29)
[error]    |	at dotty.tools.dotc.core.ProperGadtConstraint.addOneBound(GadtConstraint.scala:61)
[error]    |	at dotty.tools.dotc.core.ConstraintHandling.addBoundTransitively(ConstraintHandling.scala:316)
[error]    |	at dotty.tools.dotc.core.ConstraintHandling.addBoundTransitively$(ConstraintHandling.scala:29)
[error]    |	at dotty.tools.dotc.core.ProperGadtConstraint.addBoundTransitively(GadtConstraint.scala:61)
[error]    |	at dotty.tools.dotc.core.ProperGadtConstraint.addBound(GadtConstraint.scala:168)
[error]    |	at dotty.tools.dotc.core.TypeComparer.gadtAddLowerBound(TypeComparer.scala:116)
[error]    |	at dotty.tools.dotc.core.TypeComparer.narrowGADTBounds(TypeComparer.scala:1893)
[error]    |	at dotty.tools.dotc.core.TypeComparer.compareGADT$1(TypeComparer.scala:509)
[error]    |	at dotty.tools.dotc.core.TypeComparer.thirdTryNamed$1(TypeComparer.scala:512)
[error]    |	at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:561)
[error]    |	at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:492)
[error]    |	at dotty.tools.dotc.core.TypeComparer.compareNamed$1(TypeComparer.scala:301)
[error]    |	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:307)
[error]    |	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1309)
[error]    |	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:189)
[error]    |	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:199)
[error]    |	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:126)
[error]    |	at dotty.tools.dotc.core.TypeComparer$.topLevelSubType(TypeComparer.scala:2709)
[error]    |	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:1040)
[error]    |	at scala.quoted.runtime.impl.QuoteMatcher$.$eq$qmark$eq(QuoteMatcher.scala:336)
[error]    |	at scala.quoted.runtime.impl.QuoteMatcher$.treeMatch(QuoteMatcher.scala:129)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.scala$quoted$runtime$impl$QuotesImpl$$treeMatch(QuotesImpl.scala:3051)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$TypeMatch$.unapply(QuotesImpl.scala:3021)
```

Is there a better (and working :) ) way to achieve the above goal?</div>

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #15159
Updates buggy tests of #13230

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@pikinier20 could you investigate those bugs?

**Comment by nicolasstucki** [comment]
Thank you @pikinier20

**Comment by nicolasstucki** [comment]
@deusaquilus in this PR I found a bug in protoquill. I added an assertion to make sure that the selected member exists. The seems to try to create the type `Mod.modVal.ModVal$` which is a nonsensical type. What was this code trying to compute? 

```scala
[error] -- Error: /__w/dotty/dotty/community-build/community-projects/protoquill/quill-sql/src/test/scala/io/getquill/metaprog/StaticSpliceSpec.scala:13:56 
[error] 13 |    ctx.run { query[Person].filter(p => p.name == static(Mod.modVal)) }.string mustEqual
[error]    |                                                  ^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: module class Mod$ is not a member of (io.getquill.util.prep.Mod.modVal : String)
[error]    |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.memberType(QuotesImpl.scala:1741)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.memberType(QuotesImpl.scala:1740)
[error]    |	at io.getquill.context.StaticSpliceMacro$TermOwnerIsModule$.unapply$$anonfun$2(StaticSpliceMacro.scala:78)
[error]    |	at scala.Option.flatMap(Option.scala:283)
[error]    |	at io.getquill.context.StaticSpliceMacro$TermOwnerIsModule$.unapply(StaticSpliceMacro.scala:82)
[error]    |	at io.getquill.context.StaticSpliceMacro$.apply(StaticSpliceMacro.scala:114)
[error]    |
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from Dsl.scala:62
[error] 62 |  inline def static[T](inline value: T): T = ${ StaticSpliceMacro('value) }
[error]    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from Dsl.scala:62
[error]  3 |export Dsl._
[error]    |       ^^^
[error]     ----------------------------------------------------------------------------
```

**Comment by ckipp01** [comment]
Hey @nicolasstucki do you plan on returning back to this? Are you waiting on anything else for it? How can I help move this forward?

**Pull request closed without merging**
