### PR TITLE
Switch mapping of context bounds to using clauses in 3.6

### PR DESCRIPTION
**Pull request by odersky**
Was future before.

We can roll this out now, since we already made it an error in 3.5 to pass a normal argument to a using clause. It would be good to roll this out now since otherwise context bounds would represent an exception to the implicit priority inversion in #19300. 

See discussion at the end of #19300 for details.

### CODE REVIEW

**Comment by odersky** [comment]
This needs a change in scaladoc to recognize using clauses with evidence parameters as context bounds. Right now it seems the logic is that a context bound is recognized only if the evidence parameter is an implicit.

@Florian3k can you take this on? Alternatively, who else is working on scaladoc these days?

**Comment by Gedochao** [comment]
> Alternatively, who else is working on scaladoc these days?

Nobody else AFAIK. So it's fair game for anyone, if Mikołaj isn't available.

**Comment by tgodzik** [comment]
Shouldn't this be a quick fix around https://github.com/scala/scala3/blob/main/scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala#L633 ?

Last PR that touched it was https://github.com/scala/scala3/pull/13172

We can either wait for him or try to fix it quickly here (I think you have msot context about the change and could probably change it quickest though)

**Comment by KacperFKorban** [comment]
It looks like similar changes as in scaladoc might be needed [here](https://github.com/scala/scala3/blob/f0b3a2b2a3dc46d7269424f0987cfa490b819143/presentation-compiler/src/main/dotty/tools/pc/printer/ShortenedTypePrinter.scala#L299) and [here](https://github.com/scala/scala3/blob/f0b3a2b2a3dc46d7269424f0987cfa490b819143/compiler/src/dotty/tools/dotc/util/Signatures.scala#L502) for pc to work correctly

**Comment by odersky** [comment]
@KacperFKorban Thanks for the pointers!

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
