### PR TITLE
Report error in Setup for illegal capture refs

### LINKED ISSUE #21868: Instantiating abstract types bounded by CapSet with Nothing crashes the capture checker
## Compiler version

Latest nightly.

## Minimized code

```scala
import language.experimental.captureChecking
import caps._

trait Abstract:
    type C <: CapSet
    def boom(): Unit^{this.C^}

class Concrete extends Abstract:
    type C = Nothing
    def boom() = () // dotty.tools.dotc.cc.IllegalCaptureRef: Nothing
```

## Output

The compiler crashes with `dotty.tools.dotc.cc.IllegalCaptureRef: Nothing`.

### PR DESCRIPTION
**Pull request by bracevac**
Fixes #21868

### CODE REVIEW

**Comment by bracevac** [comment]
@noti0na1 I think it'd be good to merge this into https://github.com/scala/scala3/pull/21875

**Comment by bracevac** [comment]
The test case for this is tied to the paths to "capture set type members" that your PR fixes:
```scala
import language.experimental.captureChecking
import caps._

case class File(path: String) extends Capability

trait Abstract:
    type C <: CapSet
    def boom(): Unit^{this.C^}

class Concrete extends Abstract:
    type C = Nothing
    def boom() = () 
```
now yields
```scala
-- Error: local/i21868.scala:10:14 ---------------------------------------------
10 |    def boom() = () 
   |              ^
   |              Illegal capture reference: Nothing
Illegal capture reference: Nothing
-- Error: local/i21868.scala:6:22 ----------------------------------------------
6 |    def boom(): Unit^{this.C^}
  |                      ^^^^^^^
  |          Abstract.this.C cannot be tracked since its capture set is empty
```
And I think the second one shouldn't be reported.

**Comment by noti0na1** [comment]
I think the second error is valid, because the capture set of the upper bound of `type C <: CapSet` is empty.

**Comment by noti0na1** [comment]
It seems the function is called twice on the same type at different places, so the error is reported twice.

**Comment by bracevac** [comment]
Merged with https://github.com/scala/scala3/pull/21875

**Pull request closed without merging**
