### PR TITLE
[WIP] Match Type with no cases should not reduce to `ErrorType`

### LINKED ISSUE #19949: Unsound conformance from selection of member MatchType
Match type with no cases reduces to unreported `ErrorType`

## Compiler version

3.4.2-RC1

## Minimized code

```Scala
trait T[N]:
  type M = N match
    case 0 => Any // or anything else

val t: T[Double] = new T[Double] {}
val x: t.M = "hello"
val y: Boolean = x // compiles + ClassCastException
```

We also have the same issue when using a projection:
```scala 3
val z: T[Double]#M = "hello"
val _: Boolean = z // compiles + ClassCastException
```

Minimised from @Gedochao's https://github.com/scala/scala3/issues/19936#issuecomment-1997215624

### LINKED ISSUE #19950: Regression in `typelevel/spotted-leopards` for extension methods
## Compiler version
Last good release: 3.3.2-RC1-bin-20230623-171849f-NIGHTLY
First bad release: 3.3.2-RC1-bin-20230624-be42772-NIGHTLY
Bisect points to 9ae1598eeb9ed1004a0e12c893be04013dfa17fe

## Minimized code

```Scala
trait Apply[F[_]]:
  extension [T <: NonEmptyTuple](tuple: T)(using toMap: Tuple.IsMappedBy[F][T])
    def mapN[B](f: Tuple.InverseMap[T, F] => B): F[B] = ???

given Apply[Option] = ???
given Apply[List] = ???
given Apply[util.Try] = ???

@main def Repro = (Option(1), Option(2), Option(3)).mapN(_ + _ + _)
```

## Output

```scala
-- [E007] Type Mismatch Error: /Users/wmazur/projects/scala3/bisect/main.scala:10:18 
10 |@main def Repro = (Option(1), Option(2), Option(3)).mapN(_ + _ + _)
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |Found:    (Option[Int], Option[Int], Option[Int])
   |Required: ?{ mapN: ? }
   |Note that implicit extension methods cannot be applied because they are ambiguous;
   |both given instance given_Apply_Option and given instance given_Apply_List provide an extension method `mapN` on (Option[Int], Option[Int], Option[Int])
   |
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by EugeneFlesselle**
When match type reduction fails because none of the cases match, 
the `MatchReducer` reduces to an `ErrorType`, it does neither of:
- throwing an internal `TypeError` exception, or
- returning `NoType` which the TypeComparer (among many) would interpret as not reducing.

Since `ErrorType extends FlexType`, the returned result of the reduction will conform to anything.

Fixes #19949 
Fixes #19950

### CODE REVIEW

**Comment by EugeneFlesselle** [comment]
`pos/constvalue-of-failed-match-type.scala` fails because the `InliningTreeMap` does not handle `TypeError`s thrown by unreducible match types. We can of course handle that case there, but would also be solved by #19954 if we consider it.

**Comment by sjrd** [comment]
> `pos/constvalue-of-failed-match-type.scala` fails because the `InliningTreeMap` does not handle `TypeError`s thrown by unreducible match types. We can of course handle that case there, but it would also be solved by #19954 if we consider it.

I added this test because at least one library depended on it. I'm not sure which one off the top of my head, although I could probably dig it up. Anyway, that means we probably need to find a way to bring it back into the green.

**Comment by dwijnand** [comment]
Accepting that the resulting unsoundness is bad and needs fixing, I would consider reintroducing throwing exceptions to be throwing (ironically) the baby out with the bath water (👶🏼 💙 ).

Is it not possible to spot how this is isn't being properly propagated in type select and in however its impacting spotted-leopards?

**Comment by EugeneFlesselle** [comment]
> Is it not possible to spot how this is isn't being properly propagated in type select and in however its impacting spotted-leopards?

I've tried that approach in #19961 but I suspect we are missing other problematic cases.

**Pull request closed without merging**
