### PR TITLE
Another given priority scheme to ensure transitivity

### PR DESCRIPTION
**Pull request by odersky**
It applies the following tweaks:

 - Do treat givens as higher priority than implicits. The previous logic was faulty, but is corrected now.
 - Drop special handling of NotGiven in prioritization. The previous logic pretended to do so, but was ineffective.
 - Do use the old priority scheme for implicit/implicit pairs.
 - Do use owner score for givens as a tie breaker if after all other tests we still have an ambiguity.

### CODE REVIEW

**Comment by odersky** [comment]
Alternative to #21305

**Comment by odersky** [comment]
@WojciechMazur Can we test this one as well with the OpenCB?

**Comment by WojciechMazur** [comment]
I've started the OpenCB for 3.5.0-RC6 + this change so we can compare it directly with the results from alternative PR and don't need to care of other issues present on main. I should have results in ~3h

**Comment by WojciechMazur** [comment]
There seems to be less arnings in general when compared to previous solution
```
Given stats for 3.5.0-RC6 (baseline)
Given alternatives choice: Some(the second alternative) - 483
Given alternatives choice: Some(none - it's ambiguous) - 762
Given alternatives choice: Some(the first alternative) - 264
Projects with changed alternatives warnings - 23

Given stats for 3.5.0-RC6 + #21305
Given alternatives choice: Some(the second alternative) - 1868
Given alternatives choice: Some(none - it's ambiguous) - 21
Given alternatives choice: Some(the first alternative) - 831
Projects with changed alternatives warnings - 88

Given stats for 3.5.0-RC6 + this PR 
Given alternatives choice: Some(the second alternative) - 1437
Given alternatives choice: Some(none - it's ambiguous) - 22
Given alternatives choice: Some(the first alternative) - 215
Projects with changed alternatives warnings - 28
```

There is 1 new ambiguous choice in `com-lihaoyi/upickle` (it was not ambiguous in neither of other revisions) 
```scala
Search [1]: ReadersVersionSpecific_this.Reader[upickle.Gadt2.IsDir[V]] : choice=none
    -  (upickle.Gadt2.IsDir.rw : [V²] (implicit evidence$1: upickle.default.ReadWriter[V²]): upickle.default.ReadWriter[upickle.Gadt2.IsDir[V²]] )
    -  (upickle.default.superTypeReader : [T, V² >: T] (implicit evidence$1: scala.deriving.Mirror.ProductOf[T], evidence$2: upickle.default.Reader[V²], evidence$3: scala.deriving.Mirror.SumOf[V²], x$1: scala.util.NotGiven[upickle.core.CurrentlyDeriving[V²]]): upickle.default.Reader[T] )
```
Here're links to each of the types: 
[ReadWriter](https://github.com/com-lihaoyi/upickle/blob/7ca02cf7d30a0bff247b993e5d4ab27df7380fba/upickle/core/src/upickle/core/Types.scala#L17-L18)
[default.superTypeReader](https://github.com/com-lihaoyi/upickle/blob/7ca02cf7d30a0bff247b993e5d4ab27df7380fba/upickle/implicits/src-3/upickle/implicits/Readers.scala#L105-L106)
[Gadt2.IsDir and it's rw implicit instance](https://github.com/com-lihaoyi/upickle/blob/7ca02cf7d30a0bff247b993e5d4ab27df7380fba/upickle/test/src/upickle/AdvancedTests.scala#L82)

No new compilation failures in OpenCB, `lemonlabsuk/scala-uri` is not building successfully (failed previously)

**Comment by odersky** [comment]
> There is 1 new ambiguous choice in com-lihaoyi/upickle (it was not ambiguous in neither of other revisions)

OK, here's what goes on here. 

 - `superTypeReader` is a given and `isDir.rw` is an implicit.
 -  Both superTypeReader` and `isDir.rw` are polymorphic
 - `superTypeReader`'s type variables can be instantiated to match a supertype of `isDir.rw`'s type. This would normally
    make `isDir.rw` chosen over `superTypeReader` except that `isDir.rw` is now an implicit and therefore loses the comparison. The result is that `isDir.rw` is _not_ better than `superTypeReader` in the "wins type" contest.
 - In the other direction we alsp get a "not better" since isDir.rw's type variable cannot be instantiated to match `superTypeReade`'s result at all.

**Comment by WojciechMazur** [comment]
Based on the results in #21328 should I run additional OpenCB build with additional https://github.com/scala/scala3/pull/21325/commits/5d584078da2b9db6a98821fdc3de11a8cf5dd7d7 change?

**Comment by odersky** [comment]
No I think we should hold off with l https://github.com/scala/scala3/commit/5d584078da2b9db6a98821fdc3de11a8cf5dd7d7 unless the other PR #21328 is disappointing. I think the other PR is both nicer and might solve more problems.

**Comment by odersky** [comment]
Superseded by #21318

**Pull request closed without merging**
