### PR TITLE
improvement: Make sure Scala CLI tests are less flaky

### PR DESCRIPTION
**Pull request by tgodzik**
The expected list should be stable and we only check if the expected subset is contained

### CODE REVIEW

**Review by hamzaremmal — APPROVED** [review]
This is a big improvement but I still think that we need to have a very clear policy on what are we allowed to add in the tests

**Comment by tgodzik** [comment]
What could be a potential policy? I can remove the tests if this is a problem.

**Comment by rochala** [comment]
Wouldn't it be best if we completely remove dependency on coursier and provide CoursierCompletions via interface, just like we do with Symbol search ?

**Comment by hamzaremmal** [comment]
> What could be a potential policy? I can remove the tests if this is a problem.

@tgodzik In my opinion, we should not use dependencies outside of our control. For these tests, (if its not possible to test with some mock system) we can either publish some kind of dummy libraryon Maven Central and use it instead of using `com.lihaoyi::pprint`, `io.circe::circe-core`, ...

**Comment by tgodzik** [comment]
> Wouldn't it be best if we completely remove dependency on coursier and provide CoursierCompletions via interface, just like we do with Symbol search ?

Probably yeah. Or just use symbol search, add `searchDependency` method.

**Pull request merged**
