### PR TITLE
Fix VarianceChecker's relativeVariance

### LINKED ISSUE #21625: Invalid variance inferred / variance check failed
## Compiler version

3.5.0

## Minimized code

```scala
trait Foo[-L] {
  def test[LF, F[_ >: L] >: LF]: Unit
}
```

## Output

```scala
contravariant type L occurs in covariant position in type [_$1 >: L] >: LF of type F
```

## Expectation
Should compile.

This works for example and I am not sure that the outer lower bound should change anything.
```scala
trait Foo[-L] {
  def test[F[_ >: L]]: Unit
}
```

This also doesn't work
```scala
trait Foo[-L] {
  def test[F[_ >: L] >: Unit]: Unit
}
```

But this does:
```scala
trait Foo[-L] {
  def test[F[_ >: L] >: Nothing]: Unit
}
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #21625

### CODE REVIEW

**Review by EugeneFlesselle — COMMENTED** [review]
I am not certain the error reported in #21625 is an issue or that these changes are sound.

Though perhaps surprising, I believe the current behavior is correct to report a variance error for `test2` but not `test1` in:
```scala
trait Foo[-L]:
  def test1[F[_ >: L]]: Unit
  def test2[F[_ >: L] >: Unit]: Unit
```
That is because `test1` infers the poly-kinded lower bound `Nothing`, which avoids a variance error by preventing `L` from appearing in the lower bound entirely.

Whereas in `test2`, we have the lower bound `[X >: L] =>> Unit`, which does include `L`. Further, there do not seem to be any incorrect steps, as far as I can tell, in the variance trace (prior to the changes) which leads to the conclusion that `L` appears in a covariant position.
```
[log SetRootTree] ==> variance checking [X >: L] >: Unit of type F at 1?
[log SetRootTree]   ==> variance checking [X >: L] =>> Unit of type F at -1?
[log SetRootTree]     ==> variance checking  >: L of type F at 1?
[log SetRootTree]       ==> variance checking L of type F at -1?
[log SetRootTree] verifying type L (contravariant type L in trait Foo) is covariant at type F in method test2 in trait Foo
```

**Comment by dwijnand** [comment]
I struggled (after lots of time) to find a counter-example that causes it to crash, which isn't any proof, particularly as it's not my strong suit.  But then I also found some evidence - I think in method param symbol checking? - where only the upper bound is checked ever.  So that kind of encouraged to push forward.  Then ultimately by symmetry those "was: error" really stood out against the other cases.  So those are my 3 weakish reasons.

**Comment by EugeneFlesselle** [comment]
> I struggled (after lots of time) to find a counter-example that causes it to crash, which isn't any proof, particularly as it's not my strong suit.

Yes, I also gave it go but couldn't come up with a counter-example either given the settup is quite involved.

> But then I also found some evidence - I think in method param symbol checking? - where only the upper bound is checked ever.

I'm not familiar with that, is there a specific method you can point to?

> Then ultimately by symmetry those "was: error" really stood out against the other cases.

Yes, those can indeed look surprising at first, but I still think it is correct to have an error in both `LA` cases but only in the first of the `NL` cases. Because the `NL` cases infer the poly-kinded lower bound `Nothing` which effectively removes one-half of the checks. Whereas the `LA` cases need to consider the type lambda for both the upper and lower bound of `F`, leading to an error in both `F_LA_LB` and `F_LA_UB` but from different sides of the check.

```
type F_LA_LB[X >: L] >: X // error: >: L
type F_LA_UB[X >: L] <: X // error: >: L

type F_NL_LB[X <: L] >: X // error: <: L
type F_NL_UB[X <: L] <: X // ok
```

**Comment by dwijnand** [comment]
> > But then I also found some evidence - I think in method param symbol checking? - where only the upper bound is checked ever.
> 
> I'm not familiar with that, is there a specific method you can point to?

I misremembered.  It's not the method parameters only have their upper bound checked, it's that method parameters are checked separately than the method result type.  But that doesn't shed much light on type constructor lower bounds.

I still think the asymmetry is wrong.

Another approach, perhaps, would be to _only_ warn if the parameter is used, then a lower bound that doesn't use the type parameter wouldn't warn, and Nothing/Any wouldn't be different.

**Pull request closed without merging**
