### PR TITLE
Update asm to patched 9.7

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by Philippus** [comment]
Note that on Scala 2.13, this update fails the build: https://github.com/scala/scala/pull/10744.

**Comment by SethTisue** [comment]
marking as draft for now until we figure out what's going on over in Scala 2

**Review by SethTisue — APPROVED** [review]

**Comment by SethTisue** [comment]
> not sure if other changes are needed

it doesn't seem so, as the change Lukas made in the Scala 2 PR only affects the optimizer which doesn't exist in Scala 3

**Comment by SethTisue** [comment]
@hamzaremmal I don't know on what timetable JDK 23 should be added to the CI matrix here. We are in the process of adding it to the Scala 2 CI matrix, including the Scala 2 community build.

**Comment by timothyklim** [comment]
Is there any estimates when it'll be merged and went to nightly? Thanks

**Comment by WojciechMazur** [comment]
> Is there any estimates when it'll be merged and went to nightly? Thanks

It should already be available in 3.6.0-RC1-bin-20240826-c0cfd0f-NIGHTLY - the [commit SHA  used for that nightly](https://github.com/scala/scala3/commits/c0cfd0f) is a successor of this PR

**Pull request merged**
