### PR TITLE
Named tuples 3

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by bishabosha** [comment]
Relevant failure:
Found @experimental definition in library not listed:
scala.NamedTuple$.FutureTupleOps
scala.NamedTuple$.FutureTupleOps$
scala.Tuple$.Reverse
scala.Tuple$.ReverseOnto
scala.Tuple.reverse
scala.runtime.Tuples$.reverse

If added new experimental definitions to the library, add them to the list in tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala

Test only: sbt "scala3-bootstrapped/testCompilation tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala"

**Comment by odersky** [comment]
I don't think we should backtrack on FutureTupleOps again. This is just causes friction and statis. Any improvement to Tuple is welcome, and should not be held up. If it has been thoroughly reviewed it should not be experimental. I am going agead with the minimum changes to Tuple that make NamedTuple work and these will  not be experimental. 

It's all very good to hedge our bets, but we have seen in the past that this means progress will be delayed indefinitely. Otherwise, why would Tuple.scala still be in the bad state it is?

**Comment by sjrd** [comment]
> I am going agead with the minimum changes to Tuple that make NamedTuple work and these will not be experimental.

Yes, OK. Fine by me as long as it's only minimal additions.

**Comment by odersky** [comment]
OK, I incorporated all changes into named-tuples-2. We should do a separate effort to clean up Tuple in the next cycle. @EugeneFlesselle did a good job in https://github.com/dotty-staging/dotty/pull/41 to split into reviewable commits. Maybe we can build on that?

**Comment by sjrd** [comment]
> OK, I incorporated all changes into named-tuples-2.

OK, closing this one as superseded by #19174.

> We should do a separate effort to clean up Tuple in the next cycle. @EugeneFlesselle did a good job in [dotty-staging#41](https://github.com/dotty-staging/dotty/pull/41) to split into reviewable commits. Maybe we can build on that?

Yes, absolutely.

**Pull request closed without merging**
