### PR TITLE
Drop scala3-presentation-compiler-non-bootstrapped

### PR DESCRIPTION
**Pull request by hamzaremmal**
Drop the non bootstrapped version of the presentation compiler and only keep a single one that uses the bootstrapped compiler and library

[test_non_bootstrapped]

### CODE REVIEW

**Review by odersky — APPROVED** [review]
I am good with it, if the others agree.

**Review by tgodzik — COMMENTED** [review]
So bootstrapped version would be the one that is actually released right? Just to make sure, I don't think I've actually seen in writing what is the difference between the two.

**Comment by rochala** [comment]
We've always released only bootstrapped artifacts. As far as I remember, it was added to provide better support for Scala doc module, which builds on non-bootstrapped compiler.

**Comment by tgodzik** [comment]
> We've always released only bootstrapped artifacts. As far as I remember, it was added to provide better support for Scala doc module, which builds on non-bootstrapped compiler. We haven't really made any steps to build that support further

ach right, Metals will not support anything that only uses non-bootstrapped then. I so I guess the decision is in the compiler team whether it's ok.

**Review by tgodzik — APPROVED** [review]

**Pull request merged**
