### PR TITLE
Fix MiMa filters

### PR DESCRIPTION
**Pull request by hamzaremmal**
Fix https://github.com/scala/scala3/pull/21374#issuecomment-2286117460

### CODE REVIEW

**Comment by Kordyjan** [comment]
Is it some problem that it is solving?

**Comment by hamzaremmal** [comment]
Yes, I just linked the comment

**Comment by hamzaremmal** [comment]
I'm adding a second commit with all the missing filters right now...

**Comment by Kordyjan** [comment]
Ok, that makes sense then as a fix.

**Review by Kordyjan — APPROVED** [review]

**Comment by hamzaremmal** [comment]
Some additional information about the issue here: https://github.com/scala/scala3/pull/21374#issuecomment-2286414553

**Pull request merged**
