### PR TITLE
fix(#16610): warn ignored Scaladoc on multiple enum cases

### LINKED ISSUE #16610: scaladoc comment for multiple enum cases is silently ignored without any warning
## Compiler version
```scala
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "3.2.1"

lazy val root = (project in file("."))
  .settings(
    name := "untitled380"
  )
```

## Minimized code
```scala
/**
 * Description of enum
 */
enum MyEnum {

  /**
   * Description of case 1
   */
  case MyCase1

  /**
   * Description of case 1 and 3
   */
  case MyCase2, MyCase3
}
```
Run `sbt doc`
Notice that no documentation will be generated for `MyCase2` and `MyCase3`:

This is kinda expected (to some degree), for example because scala doc could contain references to parameters and type parameters:
```scala
/**
 * @param myParameter parameter description
 * @tparam MyTypeParameter type parameter description
 *
 */
enum TestEnum[MyTypeParameter](myParameter: Int) {
  /**
   * @param myParameterInner42 parameter description
   * @tparam MyTypeParameterInner type parameter description
   */
  case EnumMember[MyTypeParameterInner](myParameterInner42: Int)
    extends TestEnum[MyTypeParameterInner](myParameterInner42)
}
```

## Expectation
At least some warning should be printed during `sbt doc`.
Something like "Scaladoc at position ... was ignored because..."

## Actual result
The comment is silently ignored without any warning

### PR DESCRIPTION
**Pull request by i10416**
close #16610 

Before this commit, the compiler ignored Scaladoc comment on multiple enum cases without warning.

This is partly expected because the case to which the doc is attached is ambiguous, but we should at least warn users that the comment is ignored by compiler due to ambiguity and they should take an action if they want the doc to be displayed.

### CODE REVIEW

**Comment by i10416** [comment]
@Florian3k would you be kind enough to review the changes?

**Comment by Florian3k** [comment]
Hi, sorry for the delay, I've somehow missed the notification. I'll get to this ASAP.

**Comment by Florian3k** [comment]
This looks good, but to add new warning without flag we need to wait for 3.5.0.
For now, we can hide this behind a flag, eg. `-Wcheck-comments`.
Would you be able to do that? If no, let me know and we will take care of it.

**Comment by i10416** [comment]
> Would you be able to do that?

I haven't tried yet, so I'm not sure, but can I try ij?

**Comment by i10416** [comment]
https://github.com/scala/scala3/blob/a9bb881f13d032219f695d9b7c3fd5ed5c30f059/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala#L162

**Review by Florian3k — APPROVED** [review]
LGTM

**Pull request merged**
