### PR TITLE
emit generatedNonLocalClass in backend when callback is not enabled

### PR DESCRIPTION
**Pull request by bishabosha**
fixes https://github.com/scala/scala3/issues/21179

### CODE REVIEW

**Review by Gedochao — COMMENTED** [review]
LGTM, but a second opinion might be a good idea before we merge it.
Also, any chance we could add a test?

**Review by tgodzik — APPROVED** [review]
Looks good as far as I can say. Even if duplicated invocation of generatedNonLocalClass we should be good on the Bloop side as it's sets.

**Review by Gedochao — APPROVED** [review]

**Comment by bishabosha** [comment]
I dont have time today for a test - but we had confirmation from IntelliJ that it should work

**Comment by bishabosha** [comment]
I added the test @Gedochao @WojciechMazur

**Review by WojciechMazur — APPROVED** [review]

**Pull request merged**
