### PR TITLE
Refactor hasOnlyLocalInstantiation to use isLocalToCompilationUnit

### PR DESCRIPTION
**Pull request by mbovel**
Follow-up on #19803.

### CODE REVIEW

**Review by odersky — APPROVED** [review]
LGTM

**Review by dwijnand — APPROVED** [review]

**Comment by mbovel** [comment]
In `scala-parallel-collections`, MiMa complains about `AddingHashTable` not preserving binary compatibility:

```scala
private[mutable] abstract class ParHashMapCombiner[K, V](private val tableLoadFactor: Int)
  ...
  private[ParHashMapCombiner] class AddingHashTable(numelems: Int, lf: Int, _seedvalue: Int) extends HashTable[K, V, DefaultEntry[K, V]]
  ...
```

[Source](https://github.com/scala/scala-parallel-collections/blob/7d0e41ae4d09e1ddf063651e377921ec493fc5bf/core/src/main/scala/scala/collection/parallel/mutable/ParHashMap.scala#L225)

```
scala-parallel-collections: Failed binary compatibility check against org.scala-lang.modules:scala-parallel-collections_3:1.0.4! Found 1 potential problems (filtered 287)
[error]  * method this(scala.collection.parallel.mutable.ParHashMapCombiner,Int,Int,Int)Unit in class scala.collection.parallel.mutable.ParHashMapCombiner#AddingHashTable does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.parallel.mutable.ParHashMapCombiner#AddingHashTable.this")
[error] Module scala-parallel-collections:1.0.4+28-7d0e41ae-SNAPSHOT is not binary compatible with version 1.0.4. You have to relax your compatibility intention by changing the value of versionPolicyIntention.
[error] java.lang.RuntimeException: Failed binary compatibility check against org.scala-lang.modules:scala-parallel-collections_3:1.0.4! Found 1 potential problems (filtered 287)
```

[Logs](https://github.com/lampepfl/dotty/actions/runs/8157908763/job/22298606828#step:9:21321)

**Comment by hamzaremmal** [comment]
@mbovel I've disabled automerge for now to avoid having unexpected CI issues tomorrow morning.

**Comment by odersky** [comment]
This might be a blocker, unfortunately. We do get a different public interface.

**Comment by dwijnand** [comment]
I think it might be a bug in `isLocalToCompilationUnit`, it should be:
```diff
-      || accessBoundary(defn.RootClass).isContainedIn(symbol.topLevelClass)
+      || {
+        val boundary = accessBoundary(defn.RootClass)
+        val topLevelCls = symbol.topLevelClass
+        boundary != topLevelCls && boundary.isContainedIn(topLevelCls)
+      }
```

**Comment by dwijnand** [comment]
And if you want to be really ambitious, I think we should move the module logic into `isLocalToCompilationUnit` too.

So I looked at `cls.is(Private, butNot = Module)` to understand if the module part is dedundant.  I think the reason that when a class mixes in the trait, it needs to instantiate the module even if it's redudant.  So I assume there's some trait in the standard library (with Scala 2 emitted bytecode) that contains a private object that we need to correctly instantiate.  And in Scala 2 it had an outer pointer, so we need to emit an outer-pointer for it.  So I think the logic is correct there, the only progression we could do is start dropping outer pointers when it's defined in Scala 3 instead of Scala 2 - but perhaps that's not worth it.

**Pull request merged**
