### PR TITLE
Implement @use scheme

### PR DESCRIPTION
**Pull request by odersky**
- [x] Allow annotations like @use after capture types
- [x] Implement @use scheme: 
    - We allow @use on parameter types. 
    - If we narrow `cap` to a reach capability under a `@use`, the reach capability becomes use-declared.
    - We print such reach capabilities as `x*@use` for debugging.
    - A use-declared capability can leak into the method owner the parameter.
    - User-written reach capabilities of parameters whose type carries a `@use` annotation are also allowed to leak into the enclosing method..
    - On the other hand, if we pass an actual argument(-part) to (part-of) a formal parameter type that is annotated with `@use`, we charge the deep capture set of the argument to the currently enclosing environments.
 - [x] Check that overridden methods are @use correct. This means if an overridden method has @use in some parameter types, the overriding method must have these parameter types under @use as well. 
 - [x] Drop previous @unbox scheme.
 - [ ] Make sure @use appears only in covariant positions of parameters, nowhere else.
 - [ ] Infer @use annotations. If a parameter has a type containing occurrences of `cap` and the parameter is not referred to from a function result, add an implied @use to the parameter type. The idea is that we'd pass a parameter with universal capturing type only if the parameter is either returned or used in the method. So if it is not returned we can infer an @use.
 - [ ] Generalize the scheme to also handle capture set variables in addition to reach capabilities.

### CODE REVIEW

**Comment by odersky** [comment]
Built on the paths PR

**Comment by lrytz** [comment]
Good luck for https://github.com/unbox, bad luck for https://github.com/use (or their inboxes 😉). I hope no language or framework author ever thinks `@lrytz` would be a nice annotation.

**Comment by odersky** [comment]
OK, will backquote things from now on.

**Comment by bracevac** [comment]
> I hope no language or framework author ever thinks `@lrytz` would be a nice annotation.

New experimental polymorphic effect system confirmed.

**Comment by odersky** [comment]
Closing since I am no longer hopeful that this approach will work out.

**Pull request closed without merging**
